services:
  ptz-api:
    build: .
    container_name: ptz-api
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - STREAMIN_BASE_URL=http://main-api:80
    volumes:
      - ./presets.json:/app/presets.json
    networks:
      - default
      - stream_api_net
    restart: unless-stopped

networks:
  stream_api_net:
    external: true
    name: stream-service-api_default
